
NanoPlaceLoader: 
  config_path: "datasets/train/datasets/gsvcities-5/dataconfig.pkl" 
  batch_size: 32
  images_per_place: 4 
  num_workers: 4
  seed: 42

ValLoader: 
  val_set_names: ["pitts30k"]
  batch_size: 64
  num_workers: 4

NanoPlaceModel: 
  model_name: "resnet50gem"
  descriptor_dim: 512
  loss_name: "multisimilarity"
  miner_name: "multisimilarity"

Trainer: 
  max_steps: 5000
  val_check_interval: 200
  precision: "bf16-mixed"
  WandBLogger: 
    project: "nanoplace" 
    name: "gsvcities-5" 
  ModelCheckpoint: 
    dirpath: "checkpoints/gsvcities-5/" 
    filename: "gsvcities-5-{epoch:02d}-{val_recall@1_Pitts30k:.2f}"
    monitor: "val_recall@1_Pitts30k"
    mode: "max"
    save_top_k: 1


